project:
  type: website

execute:
  freeze: auto  # re-render only when source changes

website:
  title: Patrick Baylis
  favicon: "img/favicon-camping.png"
  google-analytics: 
    tracking-id: "G-EC2GDDXRGY"
    storage: "none"
    anonymize-ip: true
  navbar:
    title: Patrick Baylis
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: pdf/Baylis_CV.pdf
        text: CV
      - href: teaching.qmd
        text: Teaching
      - href: posts.qmd
        text: Blog
    right:
      - icon: github
        href: https://github.com/pbaylis
      - text: "{{< fa brands bluesky >}}" 
        href: https://bsky.app/profile/patrickbaylis.bsky.social
    page-footer:  
      right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
format:
  html:
    theme: default
    css: styles.css
    title-block-banner: false
    editor: source
    



