---
layout: post
title:  "A list of gists"
date:   2019-05-16
categories:
  - programming
tags:
  - github
---
  
I've been saving a lot of code snippets here. To keep things organized, I'm going to keep them in a single page instead.

An ideal solution would be to have an embedded, dynamically updating page that listed all of my gists by category or language. It's not obvious to me how I can do that easily right now, although there is a Gist API. 

For now, here is the [list of all of my gists](https://gist.github.com/pbaylis). And below is a hand-curated list by category:

- R
  - [Update beamer packages using TinyTex](https://gist.github.com/pbaylis/a9c267b678a52b4fd822eb927ae3b70c)
  - [Spatial interpolation](https://gist.github.com/pbaylis/7a19861b4e4544c9eef4)
  - [Padding integers with zeroes](https://gist.github.com/pbaylis/368bd67fd3c9813ad28b826b9ca512d4)
  - [Apply multiple functions to multiple columns (data.table)](https://gist.github.com/pbaylis/3b736f67aa239ba993b9674f5b5496bc)
  - [Points in polys (sf)](https://gist.github.com/pbaylis/40043fc6c73a607084a36ee491ff602d)
  - [dplyr dynamic variable names](https://gist.github.com/pbaylis/4caa0b928a5c56ce6c8f56a4e58c08d1)
- Python
  - [Unclaimed property scraping code](https://gist.github.com/pbaylis/0a31fa51108a1ab9f464)
- Stata
  - [Compute relative humidity](https://gist.github.com/pbaylis/15cdc8fd59e1888705ae)
  - [Compute heat index](https://gist.github.com/pbaylis/5cc38e5c8415d87b9b28)
  - [Create nice dummy bins](https://gist.github.com/pbaylis/7c641b91fcea1e32d3d8)
- Other
  - [Using tmux for remote commands](https://gist.github.com/pbaylis/a76402ef47a6f042445587130fd0401d)
  - [Open Bear with a daily log template](https://gist.github.com/pbaylis/db4bb881f3259aa922c990feb81fe7b3)
