---
layout: post
title: "How I'm remote teaching a big class this fall"
author: Patrick Baylis
date: 2020-08-20
categories:
  - teaching
tags:
  - pedagogy
---

I start teaching remotely in two weeks. Helping 140 students spread across the world (so many timezones!) learn about environmental economics is a daunting task. Fortunately, I have great colleagues with good ideas about how to do it. I canvassed my network on Twitter yesterday, starting with what I had planned for the course:

<center>
```{r echo=FALSE}
blogdown::shortcode('tweet', '1296525738095648772')
```
</center>

This short post led a wide-ranging thread with lots of great input from people who have thought more deeply about this. Happily, many others are following a similar mixed delivery model, where required content is available anytime, but students can also meet with me and/or their classmates in real time. But there were a few great tweaks they suggested. Having digested their input, here's the plan for the fall (also planning to post the syllabus once I've finished updating it):

1. Pre-recorded video lectures, *5-8* minutes each. 
    - I originally planned for 10-15 minutes, but [\@JenniferRaynor_](https://twitter.com/jenniferraynor_) and [\@hagertynw](https://twitter.com/hagertynw)
convinced me to try to go shorter.
    - [\@RichardTol](https://twitter.com/RichardTol) has made an amazing set of videos (his and others) available [here](https://github.com/rtol/Environmental-Economics/wiki/Videos).
2. Weekly discussion quizzes
    - These were going to be for completion only, but [\@MarinaAdshade](https://twitter.com/MarinaAdshade)'s comment (below) convinced me that they should be worth more and assessed for correctness.
    - I am a bit concerned that the grading load may be onerous for my TA, so I'm considering how to balance that.
    - [\@mattsclancy](https://twitter.com/mattsclancy) pointed me towards [LearnItFast.io](https://learnitfast.io/), which I like the look of but won't be able to get around to this year. See his [thread](https://twitter.com/mattsclancy/status/1271555608060329984) for more.
3. Weekly meeting for workshopping & questions
    - [\@mrobj](https://twitter.com/mikejrob) is planning to use this time for breakout rooms and experiments. That's an endeavor for another year for me, but feels like an exciting idea that could work even in non-pandemic years.
4. Open note, time-limited exams
    - A couple folks raised reasonable concerns about the possibility of cheating in this format.
    - [\@MarinaAdshade](https://twitter.com/MarinaAdshade) commented that she is moving more towards low-stakes assessments rather than a small number of high risk exams as a way to minimize the incentives to cheat. 
    - [\@npmagnan](https://twitter.com/npmagnan) is doing open-note exams with randomized question and answer order, plus no-backtracking. Students don't like the no-backtracking rule but it limits the ability to "collaborate".
    - This year, I've decided to take a middle ground: I'm dropping the midterm and keeping the final, while loading more weight onto the weekly discussion quizzes (see above).
    
There's a lot left to do, but I'm excited for this year for two reasons. First, this change in approach is much better than just transferring my usual in-person song and dance to Zoom. It's also more humane for students living in distant timezones. I know it's going to be hard for students to stay engaged online no matter what, but it's got to be better than, say, watching me drone on for 80 minutes straight. At the same time, having synchronous sessions available will help the students get their questions answered and hopefully provide some measure of much-needed social interaction. Finally, more low-risk assessments will hopefully help students feel like they don't need to cheat to succeed in the class.

Second, I think a lot of the additional work I put in for this course will also pay off in future, (hopefully) non-pandemic years. With a set of digestible lecture videos, I can move towards more of a flipped classroom [approach ](https://www.sciencedirect.com/science/article/pii/S1747938X19301599). Plus, having learned how to use OBS Studio to record lectures, doing so in the future will be much easier (more on the recording setup later). And since more frequent, lower risk quizzes will lower the pressure of assessments in an in-person setting as well, I hope to continue that into the future as well. Doing so will also let me implement [spaced repetition](https://www.dartmouth.edu/~cogedlab/pubs/Kang(2016,PIBBS).pdf) to help students retain information better.

Thanks to everyone, including those not mentioned above, who contributed to the discussion yesterday. As the Wisconsin motto says... Forward!


