---
title: "Work habits that work (for me)"
slug: work-habits
layout: post
date: 2021-04-09
categories: productivity
tags:
- habits
- productivity
---

I used to think a lot about productivity. I still do, but I used to, too. (Apologies to Mitch Hedberg, wherever he is.)

What is productivity? As an economist, I suppose I'm professionally obligated to define productivity as "rate of output per unit of input." But as a human and person who tries to get stuff done, I prefer to think of productivity as the state of **doing good work in a sustainable way**. (Sustainable, by the way, here refers to what is sustainable for us as people, though of course it's better if your version of productivity doesn't also burn down the rain forests or something.) In other words, how can we get the good stuff done over the long term? 

That's what this post is about. I am one of those people who thinks a lot - too much, I'll argue later - about productivity. In a previous and now somewhat cringe-inducing [post](/blog/2015-09-08-researchproductivity/), I wrote about the kinds of practices and tools that I found useful for maintaining productivity as a grad student. In the five years since I wrote that, my thinking has continued to evolve. The following post is a loose meander through that thinking. I'll start with some **caveats**, then I'll talk about some of the **principles** underlying how I approach work, a few of my favorite **habits**, **research-specific** notes, and end with a discussion of the **tools** that I typically use. I'll wrap up with a brief list of some **resources** you 

## Caveats

The **first caveat** is that I should say here that I **do not** think of myself as an exceptionally productive person! I know (and am lucky to work with) a bunch of people who are, though, and I read a lot (again, too much) on the topic. But every once in a while, I reflect on how my approach to work has shifted over the years and I can see that implementing a lot of these ideas really has allowed me to do more good work (in a sustainable way!) than I could have a few years ago.

The **second caveat** is that fail at reaching the lofty expectations of this post **all the time**. In fact, I would guess that I fail more often than I succeed. So you should think of the ideas here as **aspirational**, and that marginal improvement is still very much improvement. 

So given these two caveats, why should you listen to me at all? Well, I do think I know what productivity **looks like**. And though I certainly have a long way to go, I'm a tinkerer by nature, and of course a researcher, and I've found that documenting these ideas and discussing them with friends and colleagues has often led to helpful conversations and better work outcomes for everyone involved. I'm hopeful they do the same for you, and if they do, I'd love to [hear](https://www.twitter.com/pbaylis) about it.

## Principles

I have a small number of principles I try keep in mind when I think about being productive.

1. **The goal is to get stuff done**. This seems obvious, but it's extremely easy to get distracted. If you're a researcher like me, your "stuff" is writing good research papers and teaching well. To the extent that other tasks (e.g., ruminating about productivity...) serve those goals you should pursue them, but don't let the *means* become the *end*. 
2. **Writing is thinking**. Most people think that writing is simply transcribing ideas in your brain. It is not. Writing is a **generative** process that will help you come up with new and better ideas. Your brain is a blob of jelly that both generates **and loses track of** hundreds of brilliant ideas every hour. Harness its power by writing. 
3. **Don't use your brain as a hard drive.** Free your brain to do what it is best at: sparking ideas! Don't use to save data, ideas about how to best code something, new projects, to remember your schedule, or to maintain a list of your big goals. Write it down and let your brain move on to something else!
4. **Future-proof**. Consider the computer and the programs you're using right now. Were you using that same computer and those same programs five years ago? I doubt it. I also doubt you'll be using the same computer and programs five or ten years in the future. So future-proof whatever you can. That means: **use systems that are easily backed up** and recognize that **you will probably change tools soon** (if you're like me, very likely within six months), so don't overinvest in the ones you're using now, and make sure that you'll be able to get the data out of them easily.

## Habits

With those principles in mind, the following are a semi-categorized list of habits that I aspire to.

- On mornings
    - Morning is my most productive time. I like to get up if I can and get to work. 
        - I should say that I have a complicated relationship with coffee.
    - I try to never schedule anything in the morning, if at all possible. Not always possible.
    - The absolute best days are the ones where I start the day with thirty minutes of writing.
- On writing
    - I can't say this enough: Writing is thinking. Writing for an audience is better thinking. Writing for an *editing* audience is the best thinking.
    - Related to this, anytime you can get yourself a deadline, you will find that your ability to produce work skyrockets. It's amazing how that works.
- Planning
    - Your brain hates a bad plan. I stole that from someone, I'm not sure who.
    - New one for me: pick a "highlight" for each day that will be the centerpiece of each day.
    - I find it helpful to have different "levels" of planning. Or different timeframes, I guess. I like to plan for the day, usually with a main goal to accomplish and a bunch of other tasks I'd like to get to. But I also like to have a weekly plan. And a quarterly plan.
    - Block your schedule. I'm honestly not the best at this, but having written down when you will work on what project frees your mind from stressing about that project at other times.
    - Generate "ACTION-OUTCOME" tasks, i.e., tasks that involve creating a deliverable (as consultants would say). Having these small goals.
- I have horrible impulse control, which is probably why I need all these rules in the first place. So taking actions to reduce the possibility that I'll become distracted is helpful.
    - For example, I will often leave my phone either in my bag or in my car.
    - Having a plan before opening a screen is super important.
    - Infinity pools idea is important and compelling and related to the phone stuff. It's been useful to ask myself what my infinity pools are.
- Effort management.
    - The nights when I work late into the night almost always result in a loss of energy and motivation the next day. 
    - Much better to maintain a constant stream of work and to enjoy your leisure time, whether that's with family, friends, etc. Leisure time is recharge time.
    - Start with a small task.
    - Not everyone is like this, but I absolutely need exercise. I've come to know when I'm likely to hit lulls and try to aim my workouts for those times. That's usually just before lunch or around 2 or 3:30.
    - Quit when you're ahead. It's appealing to finish a task, but it can be better to get a bit of a win the next day.
- "No" is the most important word in the world. Especially as a junior, you are tempted to say  yes to projects, tasks, etc. Killing projects is SUPER important. Even if it's with people you like. The most painful project I've ever had to kill was with two close friends, because I wanted to keep hanging out and working with them. But the reality was, we were all using time that should have been spent elsewhere.
    - I say this with some hesitancy, because I'm aware that folks like me - white men - are not tasked with as many asks as our minority or female colleagues, particularly when it comes to things like diversity committees, so let me caveat that with the observation that folks like me should consider whether me saying no to this tasks means it will fall to someone else and that's a very challenging question.
- Email is the devil. It really is. Anything you can do to limit the flood is enormously important. Lots of recommendations here. I know Cal Newport has a new book on this, though I haven't read it.
- Get right with your mental health. Journaling, meditating, therapy, whatever works for you. I do none of them all the time, but all of them some of the time.
- It's absolutely possible to overdo this and to just become insanely task and checklist oriented. That's probably where I'm at right now, if we're honest. Try to avoid over-optimizing, especially on tasks that you're unlikely to need to revisit or repeat.

## Research-specific thoughts

If you're a researcher like me, there are a few habits that are particularly useful for our field (but likely for others, too). 

- I have never been able to make useful forward progress on more than one or MAYBE two projects where I am the primary writer or coder at a single time. It's one thing to be delegating tasks on a couple projects - that is doable, if you have the resources to do so. But leading multiple projects is a recipe for failure.
- Get to a minimum viable research product. As they say in silicon valley, **fail fast**. 
- Whenever I write code on invented dataset, it always works out better for me. Rather than deal the the messy, real dataset I can make progress on only the critical pieces. And I know they're critical because I had to construct the data. Then when I apply it to the real data, I'm much less likely to get caught up in the details.
- Pre-comment (and post-comment) your code. Instead of just starting with code, start by describing what you want the code to do. First line of a piece of code should describe what that code will do in general. Then, you can generate a series of comments that outline the functions you'll need, the steps you'll take, and so on.
- Again, write for an audience. The main reason why I generate these posts is self-serving. I am probably the primary consumer of that code.

## Tools

I hesitate to discuss tools too much (see Principle #4 above), since I know how mercurial I am with what I use. But for the record, here's the set of applications that are most often open on my computer.

- **Markdown** for as much as possible.
    - Writing, preparing lecture slides, note-taking. I even make this website using Markdown (well, [blogdown](https://bookdown.org/yihui/blogdown/)).
    - My weapon of choice is [Atom](https://atom.io/). Other people like Sublime Text. 
- [R](https://www.r-project.org/)/[RStudio](https://www.rstudio.com/) for almost all of my coding / analysis tasks. I used to use more Python and Stata, but R does almost everything I neeed now.
- [Alfred](https://www.alfredapp.com/) (OS X) to avoid hunting through my file structure. It'll change your life.
- [Roam Research](https://roamresearch.com/): Note-taking, personal task management. RR is not free, though, but right now I use it because it does the best job allowing me to quickly get ideas out of my brain and somewhere where I can find them later.
- [Github](https://github.com/) + for project management, especially across a team. The "Issues" feature is underused by researchers.

## Resources

- [Make Time](https://www.goodreads.com/book/show/37880811-make-time) (Jake Knapp and John Zeratsky). This is probably my favorite single resource on productivity. I find it much more reasonable and accessible than many of the other resources out there, which can be dogmatic.
- Most of [Cal Newport](https://www.calnewport.com/)'s books are worth a read.
- [Getting Things Done](https://gettingthingsdone.com/) (David Allen): A system for planning work that's been useful in shaping my thinking.
- [PARA System](https://fortelabs.co/blog/para/) (Tiago Forte): Helped guide how I set up my document structure. It's not perfect, but I haven't found anything better yet.
