---
menu: main
title: Home
---

Hello!

I'm an assistant professor and environmental economist at the [Vancouver School of Economics](http://economics.ubc.ca/) at the [University of British Columbia](https://www.ubc.ca/) (UBC). I study how people respond to environmental threats like climate change, air pollution, and wildfires.

<!-- and a member of the [Centre for Food, Resource and Environmental Economics](https://cfree.landfood.ubc.ca/) (CFREE) -->

<!-- **[Matt Lowe](https://mattlowe.site/) and I currently hiring a pre-doc RA for 2020 / 2021!** The RA will contribute to a set of field and natural experiment projects in behavioural development and environmental economics. You should apply [here](https://econjobmarket.org/positions/6466), be sure to fill in the separate survey on technical background, and e-mail me if you have any questions. -->

<!-- * Patrick works on questions of **how people are affected by environmental shocks**, such as climate change and natural disasters. He is interested in the human response to these shocks - how they can attenuate or accentuate the problem? He does so using spatial tools and text-based analysis to better understand our responses. His papers on suicide and temperature, electricity and temperature, and his job market paper and related papers on the impact of temperature changes on expressed sentiment are all examples of this approach. 
* His experimental work thinks about the solutions to such problems. How **can we respond better to environmental shocks**? His paper looking at how default bias affects take-up of time-varying pricing and his work examining the why people in Delhi don’t wear masks fall into this category. Privately, the next projects need to focus on interventions that *work* and have a *big effect*. This will require some *piloting*.-->

Some of my recent [work](/research/) includes estimating the impact of temperature on tweets to understand preferences for climate change, assessing the implicit subsidy of federal wildfire suppression, projecting how climate change will alter peak electricity demand, and considering how consumers respond to defaults in electricity consumption. 

My favorite projects use large datasets, natural language processing, spatial information, or all three; as a result, I do most of my data work in [R](https://www.r-project.org)/[RStudio](https://www.rstudio.com) and [Python](https://www.python.org). When not in front of my computer, you might find me [running](http://www.patrickbaylis.com/img/IMG_0613.jpg), [baking sourdough](/blog/2020-04-12-bread-notes/), or [throwing a frisbee](http://www.patrickbaylis.com/img/frisbee-montage.jpg).

Before I joined UBC, I was a postdoctoral fellow at the [Stanford Center on Food Security and the Environment](http://fse.fsi.stanford.edu/), a graduate student in [Agricultural and Resource Economics at UC-Berkeley](http://areweb.berkeley.edu), and a research assistant at the [Energy Institute at Haas](https://ei.haas.berkeley.edu).

If you'd like to schedule a meeting with me, you can do so [here](https://calendly.com/patrick-baylis/office-hours).