---
title: "Useful links"
---

# Classes
- Nick Huntington-Klein's [ECON 305](http://nickchk.com/econ305.html), "Economics, Causality, and Analytics"
  - "a new kind of econometrics class that puts causality and programming skills first, before regression or anything else."
- Grant McDermott's [EC607](https://github.com/uo-ec607/lectures), "Environmental Economics and Data Science"
  
# Books

- Clause O. Wilke on [Data Visualization](https://serialmentor.com/dataviz/)
  - He has a [blog](https://serialmentor.com/virtualbooks/) on a variety of interesting subjects
- Yihui Xie on [bookdown](https://bookdown.org/yihui/bookdown/)
  
# Data

## Wildfires

- https://wfdss.usgs.gov/wfdss/wfdss_data_downloads.shtml

## Collections of datasets

- Rebecca Thornton's [favorite data resources](https://www.rebeccathornton.net/my-favorite-data-resources/): Mostly development-related

## Weather

- NOAA [Global Surface Summary of the Day](https://catalog.data.gov/dataset/global-surface-summary-of-the-day-gsod)
  - Derived from the [Integrated Surface Database](https://www.ncdc.noaa.gov/isd)

# UBC

- [HRMS](https://paprod.adm.ubc.ca:8443/psp/paprod/EMPLOYEE/EMPL/h/?tab=PAPP_GUEST): Salary and expense reimbursements (need to be on campus or on VPN).
- [FSC](https://ssc.adm.ubc.ca/fsc/secure/home): Get classlists and submit grades.

# Code

## TeX

- [TinyTex](https://yihui.name/tinytex/): TODO, add blog post on this since I will need commands to install new stuff.
- [Paul Goldsmith-Pinkham's Beamer Tips](https://github.com/paulgp/beamer-tips)

## R

- [Library of Statistical Techniques (LOST)](https://lost-stats.github.io/)
- [Debugging R]([https://seananderson.ca/2013/08/23/debugging-r/]) (Sean Anderson): In short, use `browser()`.
- [RMarkdown templates](https://bookdown.org/yihui/rmarkdown/document-templates.html#): Good starting point for how to create RMarkdown templates.
- [R table-making principles](https://hughjonesd.github.io/huxtable/design-principles.html): Compares huxtable to everything else.
- [Why we shouldn't use dual axes (except for linear transformations)](https://blog.datawrapper.de/dualaxis/) (Lisa Charlotte Rost)

### R Packages
- [tmap](https://github.com/mtennekes/tmap): Create decent maps quickly. Probably not a full replacement for publication-quality maps with ggplot2, though.
- [modelsummary](https://github.com/vincentarelbundock/modelsummary/#installation): the stargazer killer?
- [datadrivencv](http://nickstrayer.me/datadrivencv/): reduce the burden of maintaining a CV
- [{disk.frame}](https://diskframe.com/articles/intro-disk-frame.html): Manipulate larger-than-memory datasets (similar to Spark, Dask, JuliaDB)
- [pacman](http://trinker.github.io/pacman/vignettes/Introduction_to_pacman.html) - Package manager for R
- [fixest](https://cran.r-project.org/web/packages/fixest/vignettes/fixest_walkthrough.html): Fast(est?) fixed effect estimation, includes non-linear approaches.
- [gghighlight](https://cran.r-project.org/web/packages/gghighlight/vignettes/gghighlight.html)
- [cowplot](https://github.com/wilkelab/cowplot) (Clause Wilke)
- [glue](https://github.com/tidyverse/glue): Easily combine strings.
- [patchwork](https://github.com/thomasp85/patchwork): Easily lay out ggplot figures.
- [huxtable](https://hughjonesd.github.io/huxtable/huxtable.html): Output formatted tables.
- [qs](https://github.com/traversc/qs): Faster drop-resplacement for `saveRDS` and `readRDS`. Similar to FST, but can work on any type of object.

## Github
- [Save git credentials](https://help.github.com/en/articles/caching-your-github-password-in-git)

# Conferences 

- [List of environmental economics conferences](http://caseyjwichman.com/resources/) (Casey Wichman)

# On writing 

- [J.K. Galbraith](https://www.theatlantic.com/magazine/archive/1978/03/writing-typing-and-economics/305165/)
