---
title: "RD gotchas"
description: "Notes on regression discontinuity design pitfalls, particularly regarding graphical binning approaches and the importance of controlling for the running variable."
author: "Patrick Baylis"
date: 2015-03-05
format: 
  html:
    page-layout: full
draft: true
categories:
  - econometrics
  - RD
---

# Beware the bins

- The graphical approach of RD (as advocated by M. Anderson in ARE213) is nice, but it's not a strict analogue of  regression
- Have to be careful when the bins can contain whole groups of demeaned observation
    + e.g.: a regression with multiple pre- and post- observations with unit FE where assignment to treatment was on a per-unit basis
    + Taking the mean of a bunch of sets of demeaned observations = 0
- If I want to display the regression analogue, just use the residual variation from all RHS variables except for f(X), the function of the running var, and T, the treatment assignment (which is a function of X - if X >= threshold)

# Intuition

- Still, this was a nice opportunity for me to think through some of the implications of RD.
- Nothing special about RD. It's just declaring that assignment within a certain range is as good as random, but also including the running variable to acknowledge that the slight change in the running variable could affect the outcome and must be controlled for
- *Specification is the same* as it is for any randomized treatment assignment, except that we include the running variable
    + Form can be flexible - so we can interact with treatment indicator to account for different slopes on either side, make it nonlinear, etc.
