---
layout: post
title:  "Automatically size beamer images and tables"
date:   2018-10-11
categories:
  - writing
tags:
  - latex
  - beamer
---

"Democracy is the worst form of government, except for all the others" - Winston Churchill (although [apparently](https://www.nytimes.com/2017/02/14/opinion/dont-quote-them-on-it.html) he was quoting someone else)

This is how I feel about beamer. I still haven't figured out the perfect solution. Markdown + pandoc can work, but I always end up hacking in LaTeX, since I can be particular about what my slides look like. Recently I've started using the metropolis theme, which does a lot of things better than vanilla beamer. It doesn't avoid all of the usual beamer pain, though. My least favorite (and most repetitive) activity is resizing figures and tables to fit slides properly. In preparation for an upcoming presentation, I decided to see if there was a way around that.

Here are some promising links: 

- [Scaling graphics automatically](https://tex.stackexchange.com/questions/11954/automatically-scale-big-and-small-graphics-for-beamer-presentations)
- [Scaling tables automatically](https://tex.stackexchange.com/questions/13809/resizing-a-table-by-textheight/13812)

I plan to test these out later, when I don't have a talk to prepare.